//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRPMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRPMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keylogger is paused for {0} minutes.
        /// </summary>
        internal static string PauesdStatusDescription {
            get {
                return ResourceManager.GetString("PauesdStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string PauseActionToolTip {
            get {
                return ResourceManager.GetString("PauseActionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paused.
        /// </summary>
        internal static string PausedLoggingStatusText {
            get {
                return ResourceManager.GetString("PausedLoggingStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the program has been paused.
        /// </summary>
        internal static string PausedSystemNotificationMessage {
            get {
                return ResourceManager.GetString("PausedSystemNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Paused.
        /// </summary>
        internal static string PausedSystemNotificationTitle {
            get {
                return ResourceManager.GetString("PausedSystemNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string PauseMenuCancelButton {
            get {
                return ResourceManager.GetString("PauseMenuCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause for {0} min.
        /// </summary>
        internal static string PauseMenuFirstOption {
            get {
                return ResourceManager.GetString("PauseMenuFirstOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How long would you like to pause the keylogger.
        /// </summary>
        internal static string PauseMenuQuestion {
            get {
                return ResourceManager.GetString("PauseMenuQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause for {0} min.
        /// </summary>
        internal static string PauseMenuSecondOption {
            get {
                return ResourceManager.GetString("PauseMenuSecondOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause till tomorow.
        /// </summary>
        internal static string PauseMenuThirdOption {
            get {
                return ResourceManager.GetString("PauseMenuThirdOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will start in:.
        /// </summary>
        internal static string PauseTimeLabel {
            get {
                return ResourceManager.GetString("PauseTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string RunActionToolTip {
            get {
                return ResourceManager.GetString("RunActionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to running.
        /// </summary>
        internal static string RunningLoggingStatusText {
            get {
                return ResourceManager.GetString("RunningLoggingStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keylogger is working in the background.
        /// </summary>
        internal static string RunningStatusDescription {
            get {
                return ResourceManager.GetString("RunningStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program has been started.
        /// </summary>
        internal static string RunningSystemNotificationMessage {
            get {
                return ResourceManager.GetString("RunningSystemNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program started.
        /// </summary>
        internal static string RunningSystemNotificationTitle {
            get {
                return ResourceManager.GetString("RunningSystemNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 08:00.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will start at:.
        /// </summary>
        internal static string StartTimeLabel {
            get {
                return ResourceManager.GetString("StartTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stopped.
        /// </summary>
        internal static string StoppedLoggingStatusText {
            get {
                return ResourceManager.GetString("StoppedLoggingStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The keylogger is not working, it will start working again at the specified time.
        /// </summary>
        internal static string StoppedStatusDescription {
            get {
                return ResourceManager.GetString("StoppedStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the program has been stopped.
        /// </summary>
        internal static string StoppedSystemNotificationMessage {
            get {
                return ResourceManager.GetString("StoppedSystemNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Stoped.
        /// </summary>
        internal static string StoppedSystemNotificationTitle {
            get {
                return ResourceManager.GetString("StoppedSystemNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17:30.
        /// </summary>
        internal static string StopTime {
            get {
                return ResourceManager.GetString("StopTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will stop at:.
        /// </summary>
        internal static string StopTimeLabel {
            get {
                return ResourceManager.GetString("StopTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string SystemTrayClose {
            get {
                return ResourceManager.GetString("SystemTrayClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string SystemTrayRestore {
            get {
                return ResourceManager.GetString("SystemTrayRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRPMonitor App.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
